Repository surveyjs/survey-creator, pull requests merged in 2021-07, with the labels that each got.

#1454 Implemented click to next visible page in test tab page selector for …
  packages/survey-creator-core/src/components/tabs/test.ts
  packages/survey-creator-core/tests/creator-tester.ts
  packages/survey-creator-core/tests/tabs/test.tests.ts
Labels: enhancement, v2

#1503 Work for #1203: fix title-actions in designer theme
  packages/survey-creator-core/src/survey-designer-theme/blocks/sd-title.scss
Labels: v2

#1538 Feature/issue 1537 scroll selected
  packages/survey-creator-core/src/components/question.ts
  packages/survey-creator-core/src/creator-base.ts
  packages/survey-creator-core/tests/creator-base-v1.tests.ts
  packages/survey-creator-core/tests/creator-base.tests.ts
Labels: bug, fixed

#1555 Filtering in Element Selector doesn't work in knockout version, V2 #1554
  packages/survey-creator-core/src/property-grid/object-selector.ts
  packages/survey-creator-core/tests/property-grid/object-selector.tests.ts
Labels: bug, fixed

#1557 Add an option into settings to hide/show navigation buttons in proper…
  packages/survey-creator-core/src/property-grid/property-grid-view-model.ts
  packages/survey-creator-core/src/settings.ts
  packages/survey-creator-core/tests/property-grid/property-grid-viewmodel.tests.ts
Labels: Implemented, enhancement
