Repository surveyjs/survey-creator, pull requests merged in 2021-06, with the labels that each got.

#1272 Drag And Drop: UndoRedo #1271
  packages/survey-creator-core/src/dragdrophelper.ts
Labels: enhancement

#1311 #1310 : V2 : Drag Drop : Support ESC button
  packages/survey-creator-core/src/dragdrophelper.ts
Labels: v2

#1337 Bug/1328 drag drop item value problems
  packages/survey-creator-core/src/components/creator.scss
  packages/survey-creator-core/src/dragdrophelper.ts
  packages/survey-creator-knockout/src/components/image-item-value.html
  packages/survey-creator-knockout/src/components/item-value.html
  packages/survey-creator-react/src/components/ImageItemValueWrapper.tsx
  packages/survey-creator-react/src/components/ItemValueWrapper.tsx
Labels: v2

#1323 Feature/cv2 1168
  packages/survey-creator-core/src/components/header/logo-image.scss
  packages/survey-creator-core/src/components/header/logo-image.ts
  packages/survey-creator-core/src/components/image-item-value.scss
  packages/survey-creator-core/src/components/item-value.ts
  packages/survey-creator-core/src/components/string-editor.scss
  packages/survey-creator-core/src/components/string-editor.ts
  packages/survey-creator-core/src/creator-base.ts
  packages/survey-creator-core/src/entries/index.ts
  packages/survey-creator-core/src/survey-designer-theme/blocks/sd-title.scss
  packages/survey-creator-core/tests/creator-base-v1.tests.ts
  packages/survey-creator-core/tests/creator-base.tests.ts
  packages/survey-creator-core/tests/tabs/designer.test.ts
  packages/survey-creator-knockout/package.json
  packages/survey-creator-knockout/src/components/button.ts
  packages/survey-creator-knockout/src/components/header/logo-image.html
  packages/survey-creator-knockout/src/components/header/logo-image.ts
  packages/survey-creator-knockout/src/components/image-item-value.html
  packages/survey-creator-knockout/src/components/question-image.html
  packages/survey-creator-knockout/src/components/string-editor.html
  packages/survey-creator-knockout/src/components/string-editor.ts
  packages/survey-creator-knockout/src/creator.ts
  packages/survey-creator-knockout/src/entries/index.ts
  packages/survey-creator-react/index.html
  packages/survey-creator-react/package.json
  packages/survey-creator-react/src/SurveyCreator.tsx
  packages/survey-creator-react/src/components/ImageItemValueWrapper.tsx
  packages/survey-creator-react/src/components/Page.tsx
  packages/survey-creator-react/src/components/QuestionDropdown.tsx
  packages/survey-creator-react/src/components/StringEditor.tsx
  packages/survey-creator-react/src/components/header/LogoImage.tsx
  packages/survey-creator-react/src/components/page-navigator/PageNavigator.tsx
  packages/survey-creator-react/src/components/tabs/Designer.tsx
  packages/survey-creator-react/src/entries/index.ts
  testCafe/designer/drag-drop.js
  testCafe/designer/inplace-editors.js
  testCafe/designer/logo-image.js
  testCafe/designer/page-title.js
  testCafe/designer/string-editor.js
  testCafe/designer/survey-description.js
  testCafe/helper.js
Labels: v2

#1358 Fixed issue logo adorner not rendered in Creator V1 due to image now rendered as component via async way for #1356
  packages/survey-creator/src/surveyjsObjects.ts
Labels: bug, fixed

#1396 Added isInitialized check in onPluginActivate method of ace editor json tab plugin #1395
  packages/survey-creator-core/src/components/tabs/json-editor-ace.ts
  packages/survey-creator-core/src/components/tabs/json-editor-plugin.ts
  packages/survey-creator-core/src/components/tabs/json-editor-textarea.ts
  packages/survey-creator-core/src/components/tabs/test.ts
  packages/survey-creator-knockout/src/components/tabs/test.ts
  testCafe/designer/inplace-editors.js
Labels: bug, fixed

#1439 Use prevPage and nextPage in test tab change page arrows for #1427
  packages/survey-creator-core/src/components/tabs/test.ts
Labels: bug, fixed, v2
