Repository surveyjs/survey-creator, pull requests merged in 2023-06, with the labels that each got.

#4235 Describe `overridingProperty`
  docs/images/property-grid-overridding-properties.png
  docs/property-grid.md
Labels: documentation

#4240 Add build instructions for the Angular, React, and Knockout packages
  packages/survey-creator-angular/README.md
  packages/survey-creator-knockout/README.md
  packages/survey-creator-react/README.md
Labels: documentation

#4248 onUploadFile function - Add a link to the demo
  packages/survey-creator-core/src/creator-base.ts
Labels: enhancement, documentation

#4264 PR: Image Picker with a disabled image upload option throws the The Cannot read properties of null (reading 'querySelector') exception on an attempt to reorder items
  packages/survey-creator-angular/src/adorners/image-item-value.component.html
  packages/survey-creator-core/src/components/item-value.ts
  packages/survey-creator-knockout/src/adorners/image-item-value.html
  packages/survey-creator-react/src/ImageItemValueWrapper.tsx
  testCafe/designer/drag-drop.ts
Labels: bug
