Repository surveyjs/survey-creator, pull requests merged in 2023-11, with the labels that each got.

#4892 Describe `onOpenFileChooser`
  packages/survey-creator-core/src/creator-base.ts
Labels: documentation

#4900 PR (CREATOR) (Functional Test): Imagepicker item looses controls after dragging
  testCafe/designer/drag-drop.ts
Labels: bug

#4901 PR: CREATOR: Change onDragDropAllow options
  packages/survey-creator-core/src/creator-base.ts
  packages/survey-creator-core/src/survey-elements.ts
Labels: API change

#4911 Localization docs: Create a section for information about custom locales
  docs/survey-localization-translate-surveys-to-different-languages.md
Labels: documentation

#4943 Survey Creator Overview - Update Feature List
  docs/overview.md
Labels: documentation
