Repository surveyjs/survey-creator, pull requests merged in 2023-08, with the labels that each got.

#4394 Describe / update theme-related APIs
  packages/survey-creator-core/src/creator-base.ts
  packages/survey-creator-core/src/creator-options.ts
Labels: documentation

#4425 CREATOR: PR: Ranking Question - The selectToRankEnabled setting is not available in a Property Grid
  packages/survey-creator-core/src/question-editor/definition.ts
Labels: bug

#4445 Add Theme Editor documentation
  docs/End-User-Guide.md
  docs/get-started-angular.md
  docs/get-started-knockout-jquery.md
  docs/get-started-react.md
  docs/get-started-vue.md
  docs/images/survey-creator-tabs.png
  docs/images/theme-editor.png
  docs/images/theme-export.png
  docs/images/theme-import.png
  docs/sidebar.json
  docs/theme-editor.md
Labels: documentation

#4485 PR: Custom Components - A custom icon is lost when dragging a custom component
  packages/survey-creator-core/src/components/toolbox/toolbox-tool.ts
  packages/survey-creator-core/src/survey-elements.ts
  packages/survey-creator-core/src/toolbox.ts
  visualRegressionTests/tests/designer/drag-drop.ts
  visualRegressionTests/tests/designer/etalons/drag-drop-toolbox-custom-component-icon.png
Labels: bug, user issue

#4474 PR: Toolbox Item and Drag Shortcut Item should be the same width
  packages/survey-creator-core/src/components/question.scss
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-panel-dynamic.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-panel.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost.png
Labels: bug
