Repository surveyjs/survey-creator, pull requests merged in 2024-06, with the labels that each got.

#5561 PR: Ranking -> Select to rank -> Carry forward placeholder looks not too good
  packages/survey-creator-core/src/components/question.scss
  visualRegressionTests/tests/designer/etalons/carry-forward-panel-ranking-select-to-rank-vertical.png
  visualRegressionTests/tests/designer/etalons/carry-forward-panel-ranking-select-to-rank.png
  visualRegressionTests/tests/designer/etalons/carry-forward-panel-ranking.png
  visualRegressionTests/tests/designer/surface.ts
Labels: bug

#5528 PR: The onDragStart and onDragEnd events do not have parameter descriptions in the docs
  packages/survey-creator-core/src/creator-base.ts
Labels: bug, documentation

#5575 Property Grid: Update hints for the "Inner panel collapse state" and "Time limit to complete one page" properties
  packages/survey-creator-core/src/localization/english.ts
  visualRegressionTests/tests/designer/etalons/side-bar-search-question-group.png
Labels: enhancement
