Repository surveyjs/survey-creator, pull requests merged in 2024-02, with the labels that each got.

#5181 Describe `enableIf` for custom properties
  docs/property-grid-customization.md
Labels: documentation

#5199 PR: Message Box Issue
  packages/survey-creator-core/src/components/simulator.scss
Labels: bug

#5229 PR: Themes Tab - The 'Yes, reset the theme' button appears beyond the popup window's boundaries
  packages/survey-creator-core/src/components/tabs/theme-plugin.ts
Labels: bug, user issue, theme builder
