Repository surveyjs/survey-creator, pull requests merged in 2024-08, with the labels that each got.

#5761 `onSetPropertyEditorOptions`: Add docs for the `editorOptions` parameter's properties
  packages/survey-creator-core/src/creator-events-api.ts
Labels: documentation

#5766 Property Grid: Update hints for the "Question title alignment" property
  packages/survey-creator-core/src/localization/english.ts
Labels: enhancement

#5792 PR: Wrong expression items' text color on hover + wrong title color
  packages/survey-creator-core/src/components/tabs/logic-ui.scss
  packages/survey-creator-core/src/components/tabs/logic.scss
Labels: bug

#5800 Update survey-creator-js README
  README.md
  packages/survey-creator-core/src/creator-base.ts
  packages/survey-creator-js/README.md
Labels: documentation

#5803 Docs: Add links to the Manage Toolbox Subitems help topic
  packages/survey-creator-core/src/toolbox.ts
Labels: documentation
