Repository surveyjs/survey-creator, pull requests merged in 2024-11, with the labels that each got.

#6105 PR: Creator v2.0: Issues
  packages/survey-creator-core/src/components/question.scss
  packages/survey-creator-core/src/components/tabs/translation.scss
  packages/survey-creator-core/src/images-v1/dropper-16x16.svg
  packages/survey-creator-core/src/images-v2/dropper-16x16.svg
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-in-collapsed-page.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-in-collapsed-panel.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-over-custom-widget.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-scroll.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-page.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-panel-dynamic.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-panel.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-toolbox-custom-component-icon.png
  visualRegressionTests/tests/designer/etalons/drag-drop-in-collapsed-page.png
  visualRegressionTests/tests/designer/etalons/drag-drop-in-collapsed-panel.png
  visualRegressionTests/tests/designer/etalons/drag-drop-over-custom-widget.png
  visualRegressionTests/tests/designer/etalons/drag-drop-scroll.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-page.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-panel-dynamic.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-panel.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost.png
  visualRegressionTests/tests/designer/etalons/drag-drop-toolbox-custom-component-icon.png
Labels: v2.0

#6154 Property Grid: Change the Pages placeholder
  packages/survey-creator-core/src/localization/arabic.ts
  packages/survey-creator-core/src/localization/bulgarian.ts
  packages/survey-creator-core/src/localization/croatian.ts
  packages/survey-creator-core/src/localization/czech.ts
  packages/survey-creator-core/src/localization/danish.ts
  packages/survey-creator-core/src/localization/dutch.ts
  packages/survey-creator-core/src/localization/english.ts
  packages/survey-creator-core/src/localization/finnish.ts
  packages/survey-creator-core/src/localization/french.ts
  packages/survey-creator-core/src/localization/german.ts
  packages/survey-creator-core/src/localization/hebrew.ts
  packages/survey-creator-core/src/localization/hungarian.ts
  packages/survey-creator-core/src/localization/indonesian.ts
  packages/survey-creator-core/src/localization/italian.ts
  packages/survey-creator-core/src/localization/japanese.ts
  packages/survey-creator-core/src/localization/korean.ts
  packages/survey-creator-core/src/localization/malay.ts
  packages/survey-creator-core/src/localization/mongolian.ts
  packages/survey-creator-core/src/localization/norwegian.ts
  packages/survey-creator-core/src/localization/persian.ts
  packages/survey-creator-core/src/localization/polish.ts
  packages/survey-creator-core/src/localization/portuguese.ts
  packages/survey-creator-core/src/localization/romanian.ts
  packages/survey-creator-core/src/localization/russian.ts
  packages/survey-creator-core/src/localization/simplified-chinese.ts
  packages/survey-creator-core/src/localization/slovak.ts
  packages/survey-creator-core/src/localization/spanish.ts
  packages/survey-creator-core/src/localization/swedish.ts
  packages/survey-creator-core/src/localization/thai.ts
  packages/survey-creator-core/src/localization/traditional-chinese.ts
  packages/survey-creator-core/src/localization/turkish.ts
  packages/survey-creator-core/tests/property-grid/property-grid-v1.tests.ts
Labels: enhancement

#6155 PR: A question is not selected on a design surface if a user clicks a question's input field area
  functionalTests/designer/surface.ts
  packages/survey-creator-core/src/components/question.scss
Labels: bug, usability, minor, user issue
