Repository surveyjs/survey-creator, pull requests merged in 2024-05, with the labels that each got.

#5451 Update the English localization dictionary
  packages/survey-creator-core/src/localization/english.ts
  packages/survey-creator-core/tests/tabs/logic-v1.tests.ts
  packages/survey-creator-core/tests/tabs/logic.tests.ts
  testCafe/designer/logic.ts
  visualRegressionTests/tests/designer/etalons/logic-action-hover.png
  visualRegressionTests/tests/designer/etalons/logic-condition-overflow-text.png
  visualRegressionTests/tests/designer/etalons/logic-fast-entry-empty.png
  visualRegressionTests/tests/designer/etalons/logic-fast-entry.png
  visualRegressionTests/tests/designer/etalons/logic-panel-actions.png
  visualRegressionTests/tests/designer/etalons/logic-question-actions.png
  visualRegressionTests/tests/designer/etalons/logic-tab-one-rule-content.png
  visualRegressionTests/tests/designer/etalons/logic-tab-rule-action-row.png
  visualRegressionTests/tests/designer/etalons/logic-tab-rule-content.png
  visualRegressionTests/tests/designer/etalons/restful-properties.png
  visualRegressionTests/tests/designer/etalons/translation-tab-show-all-strings.png
Labels: enhancement

#5452 PR: Image Picker - A screen reader doesn't announce the Add New item button
  packages/survey-creator-angular/src/adorners/image-item-value.component.html
  packages/survey-creator-core/src/components/image-item-value.ts
  packages/survey-creator-knockout/src/adorners/image-item-value.html
  packages/survey-creator-react/src/ImageItemValueWrapper.tsx
  packages/survey-creator-vue/src/adorners/ImageItemValue.vue
Labels: bug, accessibility, user issue

#5477 Fix the `onCanShowProperty` event
  packages/survey-creator-core/src/creator-base.ts
Labels: bug, documentation

#5479 onUploadFile: Make the `fileUrl` parameter in `options.callback` optional
  packages/survey-creator-core/src/creator-events-api.ts
Labels: bug

#5481 Add the `name` property to the `ModifiedEvent` interface
  packages/survey-creator-core/src/creator-events-api.ts
Labels: bug

#5431 PR: Question drag-n-drop issues
  packages/survey-creator-core/src/components/question.scss
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-empty-panel-dynamic.png
Labels: bug

#5491 PR: CREATOR: Property Grid - Page Collection Editor - A page drag icon appears far from the mouse pointer
  visualRegressionTests/tests/designer/drag-drop.ts
  visualRegressionTests/tests/designer/etalons/drag-drop-matrix-pg-choices-scroll.png
Labels: bug, user issue

#5504 Describe the `addPluginTab` method
  packages/survey-creator-core/src/creator-base.ts
Labels: documentation
