Repository surveyjs/survey-creator, pull requests merged in 2024-12, with the labels that each got.

#6177 PR: TextArea: A question is not selected on a design surface if a user clicks a question's input field area
  functionalTests/designer/surface.ts
  packages/survey-creator-core/src/components/question.scss
Labels: bug, usability, minor, user issue

#6173 PR: Creator v2.0: Design Surface: Dragged Question
  packages/survey-creator-core/src/components/question.scss
Labels: v2.0

#6097 PR: Creator: Library Only: Dynamic matrix's row drag-n-drop
  packages/survey-creator-core/src/components/matrix-cell.scss
  visualRegressionTests-V2/tests/designer/etalons/design-surface-matrixdynamic-with-drag-drop.png
  visualRegressionTests/tests/designer/etalons/design-surface-matrixdynamic-with-drag-drop.png
  visualRegressionTests/tests/designer/surface.ts
Labels: enhancement

#6107 PR: Creator v2.0: PG editors: Disabled state
  packages/survey-creator-core/src/components/tabs/translation.scss
  packages/survey-creator-core/src/property-grid-theme/blocks/spg-checkbox.scss
  packages/survey-creator-core/src/property-grid-theme/blocks/spg-input.scss
  packages/survey-creator-core/src/property-grid-theme/blocks/spg-question.scss
  packages/survey-creator-react/src/adorners/Question.tsx
  visualRegressionTests-V2/tests/designer/etalons/bindings-editor.png
  visualRegressionTests-V2/tests/designer/etalons/color-editor-title-location-left-focus.png
  visualRegressionTests-V2/tests/designer/etalons/color-editor-title-location-left.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-item-values-dropdown--mobile.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-item-values-ranking--dragging.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-item-values-ranking--hover.png
  visualRegressionTests-V2/tests/designer/etalons/dropdown-editor-title-location-left-focus.png
  visualRegressionTests-V2/tests/designer/etalons/dropdown-editor-title-location-left.png
  visualRegressionTests-V2/tests/designer/etalons/file-editor-title-location-left-focus.png
  visualRegressionTests-V2/tests/designer/etalons/file-editor-title-location-left.png
  visualRegressionTests-V2/tests/designer/etalons/pg-input-readonly.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line-date.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line-focus-date.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line-focus.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line-narrow-date.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line-narrow.png
  visualRegressionTests-V2/tests/designer/etalons/properties-on-one-line.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-search-general-group-after-next.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-search-general-group.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-search-question-group.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-tabbed-property-grid-theme-appearance-advanced-hover.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-tabbed-property-grid-theme-appearance-advanced.png
  visualRegressionTests-V2/tests/designer/etalons/side-bar-tabbed-property-grid-translation-general.png
  visualRegressionTests-V2/tests/designer/etalons/small-dropdown-1-not-selected.png
  visualRegressionTests-V2/tests/designer/etalons/spin-editor-title-location-left-focus.png
  visualRegressionTests-V2/tests/designer/etalons/spin-editor-title-location-left.png
  visualRegressionTests-V2/tests/designer/etalons/translation-auto-translate-popup-enabled-dropdown.png
  visualRegressionTests-V2/tests/designer/etalons/translation-auto-translate-popup.png
  visualRegressionTests-V2/tests/designer/etalons/translation-property-grid.png
  visualRegressionTests/tests/designer/etalons/pg-input-readonly.png
  visualRegressionTests/tests/designer/etalons/side-bar-search-general-group-after-next.png
  visualRegressionTests/tests/designer/etalons/side-bar-search-general-group.png
  visualRegressionTests/tests/designer/etalons/side-bar-search-question-group.png
Labels: v2.0

#6183 PR: Incorrect positioning of drag-n-drop indicators after designer surface scaling.
  packages/survey-creator-core/src/components/page.scss
  packages/survey-creator-core/src/components/question.scss
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-scroll.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost.png
  visualRegressionTests/tests/designer/etalons/drag-drop-scroll.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests/tests/designer/etalons/drag-drop-survey-element-ghost.png
Labels: v2.0

#6198 PR: Creator: DnD: Panels: Drag Indicator
  packages/survey-creator-core/src/components/row.scss
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-indicator-inside-panel-rows.png
  visualRegressionTests/tests/designer/drag-drop.ts
  visualRegressionTests/tests/designer/etalons/drag-drop-indicator-inside-panel-rows.png
Labels: bug

#6231 PR: Creator V2: Localization PG Layout
  packages/survey-creator-core/src/components/tabs/translation.scss
  visualRegressionTests-V2/tests/designer/etalons/translation-auto-translate-popup-enabled-dropdown.png
  visualRegressionTests-V2/tests/designer/etalons/translation-property-grid.png
  visualRegressionTests/tests/designer/etalons/translation-auto-translate-popup-enabled-dropdown.png
  visualRegressionTests/tests/designer/etalons/translation-property-grid.png
Labels: v2.0

#6256 Fix #6241 - The Input Type Text should be translated as 'Text' instead of 'SMS'
  packages/survey-creator-core/src/localization/dutch.ts
  packages/survey-creator-core/src/localization/french.ts
  packages/survey-creator-core/src/localization/hungarian.ts
  packages/survey-creator-core/src/localization/swedish.ts
Labels: bug, user issue

#6274 PR: Creator V2: remove default hover delays for pages, questions, titles, and descriptions
  packages/survey-creator-core/src/components/string-editor.scss
  packages/survey-creator-core/src/creator-base.ts
Labels: v2.0

#6308 PR: V2 Issues
  packages/survey-creator-angular/src/tabs/preview/survey-results.component.html
  packages/survey-creator-core/src/components/question-dropdown.scss
  packages/survey-creator-core/src/components/question.scss
  packages/survey-creator-core/src/components/results.scss
  packages/survey-creator-core/src/survey-elements.ts
  packages/survey-creator-knockout/src/results.html
  packages/survey-creator-react/src/Results.tsx
  packages/survey-creator-vue/src/tabs/preview/SurveyResults.vue
  visualRegressionTests-V2/tests/designer/etalons/collapsed-dropdown.png
  visualRegressionTests-V2/tests/designer/etalons/complete-tab-results-part.png
  visualRegressionTests-V2/tests/designer/etalons/complete-tab-results-via-json.png
  visualRegressionTests-V2/tests/designer/etalons/complete-tab-results-via-table-1.png
  visualRegressionTests-V2/tests/designer/etalons/complete-tab-results-via-table-2.png
  visualRegressionTests-V2/tests/designer/etalons/complete-tab-upper-part.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-in-collapsed-page.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-in-collapsed-panel.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-indicator-inside-panel-rows.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-over-custom-widget.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-scroll.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-page.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-panel-dynamic.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-empty-panel.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost-page-4.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-survey-element-ghost.png
  visualRegressionTests-V2/tests/designer/etalons/drag-drop-toolbox-custom-component-icon.png
  visualRegressionTests-V2/tests/designer/etalons/not-collapsed-dropdown.png
  visualRegressionTests-V2/tests/designer/etalons/small-dropdown-1-not-selected.png
  visualRegressionTests-V2/tests/designer/etalons/small-dropdown-1-selected.png
  visualRegressionTests-V2/tests/designer/etalons/test-tab-background-image.png
  visualRegressionTests/tests/designer/etalons/complete-tab-results-part.png
  visualRegressionTests/tests/designer/etalons/complete-tab-results-via-json.png
  visualRegressionTests/tests/designer/etalons/complete-tab-upper-part.png
  visualRegressionTests/tests/designer/etalons/test-tab-background-image.png
Labels: v2.0
